// Demo configuration — loaded when URL contains ?demo=1
// WAV files must be placed under ./wav/ on the server.
// All fields are optional; omit to keep defaults.

export const DEMO_CONFIG = {
  bpm:          120,
  masterVol:    0.85,
  masterFilter: 0,      // -1 (LPF max) … 0 (flat) … +1 (HPF max)
  delayTime:    350,    // ms

  tracks: [
    {
      file:    './wav/kick.wav',
      name:    'Kick',
      volume:  0,
      pan:     0,
      length:  '1bar',
      timing:  0,
      send:    0,
      muted:   false,
    },
    {
      file:    './wav/hihat.wav',
      name:    'Hi-hat',
      volume:  0,
      pan:     0,
      length:  '1bar',
      timing:  0,
      send:    0,
      muted:   false,
    },
    {
      file:    './wav/snare.wav',
      name:    'Snare',
      volume:  0,
      pan:     0,
      length:  '1bar',
      timing:  0,
      send:    0,
      muted:   false,
    },
    {
      file:    './wav/clap.wav',
      name:    'Clap',
      volume:  0,
      pan:     0,
      length:  '1bar',
      timing:  0,
      send:    0,
      muted:   false,
    },
 
    {
      file:    './wav/bass.wav',
      name:    'Bass',
      volume:  0,
      pan:     0,
      length:  '2bars',
      timing:  0,
      send:    0,
      muted:   false,
    },
    {
      file:    './wav/synth.wav',
      name:    'Synth',
      volume:  0,
      pan:     0,
      length:  '2bars',
      timing:  0,
      send:    0.3,
      muted:   false,
    },
    {
      file:    './wav/snareroll.wav',
      name:    'Snare Roll',
      volume:  0,
      pan:     0,
      length:  '2bars',
      timing:  0,
      send:    0.3,
      muted:   false,
    },
    {
      file:    './wav/cymbal.wav',
      name:    'Ride Cymbal',
      volume:  0,
      pan:     0,
      length:  '2bars',
      timing:  0,
      send:    0,
      muted:   false,
    },
    {
      file:    './wav/sfx1.wav',
      name:    'SFX 1',
      volume:  0,
      pan:     0,
      length:  '4bar',
      timing:  0,
      send:    0.2,
      muted:   false,
    },
    {
      file:    './wav/sfx2.wav',
      name:    'SFX 2',
      volume:  0,
      pan:     0,
      length:  '2bars',
      timing:  0,
      send:    0.2,
      muted:   false,
    },
    {
      file:    './wav/sfx3.wav',
      name:    'SFX 3',
      volume:  0,
      pan:     0,
      length:  '2bars',
      timing:  0,
      send:    0.2,
      muted:   false,
    },
    {
      file:    './wav/sfx4.wav',
      name:    'SFX 4',
      volume:  0,
      pan:     0,
      length:  '2bars',
      timing:  0,
      send:    0.2,
      muted:   false,
    },
  ],

  // Bar counter wraps at this value and resets to 1 (demo mode only).
  maxbars: 80,

  // Sequencer: apply a scene when the (wrapped) bar number is reached (demo mode only).
  // bar is 1-indexed and matches the displayed bar counter.
  sequencer: [
    { bar:  1, scene: 1 },
    { bar: 17, scene: 2 },
    { bar: 31, scene: 3 },
    { bar: 33, scene: 4 },
    { bar: 48, scene: 5 },
    { bar: 49, scene: 6 },
    { bar: 65, scene: 7 },
  ],

  // Optional: pre-defined scenes (0–9).
  // Each scene is an array of per-track states identified by name.
  // Omit any scene key to leave that slot empty.
  // volume / pan / muted are optional; omitted fields fall back to the track's loaded value.
  scenes: {
    1: [
      { name: 'Kick',        volume: 1.0, pan:  0.0, muted: false  },
      { name: 'Hi-hat',      volume: 0.0, pan:  0.1, muted: false  },
      { name: 'Snare',       volume: 0.0, pan:  0.6, muted: false  },
      { name: 'Clap',        volume: 0.0, pan: -0.6, muted: false  },
      { name: 'Bass',        volume: 0.5, pan: -0.1, muted: false  },
      { name: 'Synth',       volume: 0.1, pan:  0.3, muted: false  },
      { name: 'Snare Roll',  volume: 0.0, pan:  0.3, muted: false  },
      { name: 'Ride Cymbal', volume: 0.0, pan: -0.3, muted: false  },
      { name: 'SFX 1',       volume: 0.0, pan:  0.8, muted: false  },
      { name: 'SFX 2',       volume: 0.4, pan: -0.5, muted: false  },
      { name: 'SFX 3',       volume: 0.3, pan:  0.5, muted: false  },
      { name: 'SFX 4',       volume: 0.0, pan: -0.8, muted: false  },
    ],

    2: [
      { name: 'Kick',        volume: 1.0, pan:  0.0, muted: false  },
      { name: 'Hi-hat',      volume: 0.5, pan:  0.1, muted: false  },
      { name: 'Snare',       volume: 0.0, pan:  0.6, muted: false  },
      { name: 'Clap',        volume: 0.0, pan: -0.6, muted: false  },
      { name: 'Bass',        volume: 0.9, pan: -0.1, muted: false  },
      { name: 'Synth',       volume: 0.1, pan:  0.3, muted: false  },
      { name: 'Snare Roll',  volume: 0.0, pan:  0.3, muted: false  },
      { name: 'Ride Cymbal', volume: 0.0, pan: -0.3, muted: false  },
      { name: 'SFX 1',       volume: 0.0, pan:  0.8, muted: false  },
      { name: 'SFX 2',       volume: 0.4, pan: -0.5, muted: false  },
      { name: 'SFX 3',       volume: 0.3, pan:  0.5, muted: false  },
      { name: 'SFX 4',       volume: 0.0, pan: -0.8, muted: false  },
    ],

    3: [
      { name: 'Kick',        volume: 1.0, pan:  0.0, muted: true  },
      { name: 'Hi-hat',      volume: 0.5, pan:  0.1, muted: true  },
      { name: 'Snare',       volume: 0.0, pan:  0.6, muted: false  },
      { name: 'Clap',        volume: 0.0, pan: -0.6, muted: false  },
      { name: 'Bass',        volume: 0.9, pan: -0.1, muted: false  },
      { name: 'Synth',       volume: 0.1, pan:  0.3, muted: false  },
      { name: 'Snare Roll',  volume: 0.0, pan:  0.3, muted: false  },
      { name: 'Ride Cymbal', volume: 0.0, pan: -0.3, muted: false  },
      { name: 'SFX 1',       volume: 0.0, pan:  0.8, muted: false  },
      { name: 'SFX 2',       volume: 0.4, pan: -0.5, muted: false  },
      { name: 'SFX 3',       volume: 0.3, pan:  0.5, muted: false  },
      { name: 'SFX 4',       volume: 0.0, pan: -0.8, muted: false  },
    ],

    4: [
      { name: 'Kick',        volume: 1.0, pan:  0.0, muted: false  },
      { name: 'Hi-hat',      volume: 0.5, pan:  0.1, muted: false  },
      { name: 'Snare',       volume: 0.3, pan:  0.6, muted: false  },
      { name: 'Clap',        volume: 0.3, pan: -0.6, muted: false  },
      { name: 'Bass',        volume: 0.9, pan: -0.1, muted: false  },
      { name: 'Synth',       volume: 0.4, pan:  0.3, muted: false  },
      { name: 'Snare Roll',  volume: 0.0, pan:  0.3, muted: false  },
      { name: 'Ride Cymbal', volume: 0.7, pan: -0.3, muted: false  },
      { name: 'SFX 1',       volume: 0.0, pan:  0.8, muted: false  },
      { name: 'SFX 2',       volume: 0.4, pan: -0.5, muted: false  },
      { name: 'SFX 3',       volume: 0.3, pan:  0.5, muted: false  },
      { name: 'SFX 4',       volume: 0.0, pan: -0.8, muted: false  },
    ],

    5: [
      { name: 'Kick',        volume: 1.0, pan:  0.0, muted: false  },
      { name: 'Hi-hat',      volume: 0.5, pan:  0.1, muted: false  },
      { name: 'Snare',       volume: 0.0, pan:  0.6, muted: false  },
      { name: 'Clap',        volume: 0.3, pan: -0.6, muted: false  },
      { name: 'Bass',        volume: 0.9, pan: -0.1, muted: false  },
      { name: 'Synth',       volume: 0.4, pan:  0.3, muted: false  },
      { name: 'Snare Roll',  volume: 0.9, pan:  0.3, muted: false  },
      { name: 'Ride Cymbal', volume: 0.7, pan: -0.3, muted: false  },
      { name: 'SFX 1',       volume: 0.0, pan:  0.8, muted: false  },
      { name: 'SFX 2',       volume: 0.4, pan: -0.5, muted: false  },
      { name: 'SFX 3',       volume: 0.3, pan:  0.5, muted: false  },
      { name: 'SFX 4',       volume: 0.0, pan: -0.8, muted: false  },
    ],

    6: [
      { name: 'Kick',        volume: 0.0, pan:  0.0, muted: false  },
      { name: 'Hi-hat',      volume: 0.0, pan:  0.1, muted: false  },
      { name: 'Snare',       volume: 0.0, pan:  0.6, muted: false  },
      { name: 'Clap',        volume: 0.0, pan: -0.6, muted: false  },
      { name: 'Bass',        volume: 0.9, pan: -0.1, muted: false  },
      { name: 'Synth',       volume: 0.4, pan:  0.3, muted: false  },
      { name: 'Snare Roll',  volume: 0.0, pan:  0.3, muted: false  },
      { name: 'Ride Cymbal', volume: 0.3, pan: -0.3, muted: false  },
      { name: 'SFX 1',       volume: 0.0, pan:  0.8, muted: false  },
      { name: 'SFX 2',       volume: 0.4, pan: -0.5, muted: false  },
      { name: 'SFX 3',       volume: 0.3, pan:  0.5, muted: false  },
      { name: 'SFX 4',       volume: 0.0, pan: -0.8, muted: false  },
    ],

    7: [
      { name: 'Kick',        volume: 1.0, pan:  0.0, muted: false  },
      { name: 'Hi-hat',      volume: 0.0, pan:  0.1, muted: false  },
      { name: 'Snare',       volume: 0.0, pan:  0.6, muted: false  },
      { name: 'Clap',        volume: 0.0, pan: -0.6, muted: false  },
      { name: 'Bass',        volume: 0.9, pan: -0.1, muted: false  },
      { name: 'Synth',       volume: 0.4, pan:  0.3, muted: false  },
      { name: 'Snare Roll',  volume: 0.0, pan:  0.3, muted: false  },
      { name: 'Ride Cymbal', volume: 0.3, pan: -0.3, muted: false  },
      { name: 'SFX 1',       volume: 0.0, pan:  0.8, muted: false  },
      { name: 'SFX 2',       volume: 0.4, pan: -0.5, muted: false  },
      { name: 'SFX 3',       volume: 0.3, pan:  0.5, muted: false  },
      { name: 'SFX 4',       volume: 0.0, pan: -0.8, muted: false  },
    ],

  },
};
